[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "Ti_Oxidation"
version = "0.1.0"

[project.scripts]
rdf_layer = "ti_oxidation.rdf_layer_corrected:main"
supercell_k = "ti_oxidation.supercell_eval:main"
lbfgsb_supercell = "ti_oxidation.lbfgs_search:main"
no_flying = "ti_oxidation.remove_flyers:main"
box_search_gen = "ti_oxidation.lattice_param_pe_surface:main"
o_blanky = "ti_oxidation.blanket_O:main"
beauty = "ti_oxidation.plot_cli:main"
merge_log = "ti_oxidation.merge_log:main"

[tool.pytest.ini_options]
pythonpath = ["src"]

