[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "Ti_Oxidation"
version = "0.1.0"

[project.scripts]
rdf_layer = "ti_oxidation.rdf_layer_corrected:main"
supercell_k = "ti_oxidation.supercell_eval:main"
lbfgsb_supercell = "ti_oxidation.lbfgs_search:main"
no_flying = "ti_oxidation.remove_flyers:main"

[tool.pytest.ini_options]
pythonpath = ["src"]

